[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions."___netlify-server-handler"]
  included_files = ["node_modules/.prisma/client/**", "node_modules/@prisma/client/runtime/libquery_engine-rhel-openssl-3.0.x.so.node"]
